settings:
  session_name: "tg_dispatcher"
  loop_interval: 300    # 轮询间隔（秒）
  log_level: "INFO"

tasks:
  - name: "Twitter_Article"
    enable: true
    sources: [-5184448717,-5097290219] # 请替换为实际的 ID
    keywords: ["twitter.com", "x.com"]
    output:
      path: "./data/x/x_url.csv"
      format: "csv"

  - name: "WeChat_GZH"
    enable: true
    sources: [-5175449542,-5097290219]    # "all" 表示监听所有已配置的群组
    keywords: ["mp.weixin.qq.com"]
    output:
      path: "./data/wechat/wechat_url.csv"
      format: "csv"
      
  - name: "X_Video"
    enable: true
    sources: [-5204811810]    # "all" 表示监听所有已配置的群组
    keywords: ["twitter.com", "x.com", "vxtwitter.com", "fxtwitter.com"]
    output:
      path: "./data/x/x_video_url.csv"
      format: "csv"

  - name: "Youtube_Video"
    enable: true
    sources: [-5298749551,-5097290219]    # "all" 表示监听所有已配置的群组
    keywords: ["youtube.com", "youtu.be"]
    output:
      path: "./data/youtube/youtube_url.csv"
      format: "csv"     
      
  - name: "Douyin_Video"
    enable: true
    # 如果想从所有加入的群组中抓取，填 ["all"]；如果是特定群，填 ID 列表
    sources: [-5152483212,-5097290219]
    # 关键词包含短链和长链域名，确保能被路由捕获
    keywords: ["douyin.com", "v.douyin.com"]
    output:
      path: "./data/douyin/douyin_videos.csv"
      format: "csv"
